using System;
using System.Text;
using System.Windows;
using WowQuestTtsTool.Services;

namespace WowQuestTtsTool
{
    /// <summary>
    /// Interaktionslogik fuer ManualTextGenerationWindow.xaml
    /// Fenster fuer den manuellen Text-KI-Modus (Browser-Premium statt API).
    /// </summary>
    public partial class ManualTextGenerationWindow : Window
    {
        private readonly Quest _quest;
        private readonly string _originalText;

        /// <summary>
        /// Ergebnis der manuellen Text-Generierung.
        /// </summary>
        public string? EnhancedText { get; private set; }

        /// <summary>
        /// Gibt an, ob der Benutzer den Text uebernommen hat.
        /// </summary>
        public bool WasApplied { get; private set; }

        /// <summary>
        /// System-Prompt fuer die Hoerbuch-Optimierung (gleich wie im LlmTextEnhancerService).
        /// </summary>
        private const string SystemPrompt = @"Du bist ein erfahrener Hoerbuch-Autor und Uebersetzer, spezialisiert auf Fantasy-Rollenspiele wie World of Warcraft.

Deine Aufgabe: Wandle knappe Quest-Texte in lebendige, hoerbuchreife Erzaehlungen um.

WICHTIGE REGELN:
1. INHALT NICHT AENDERN: Alle Fakten, Zahlen, Namen und Ziele muessen exakt erhalten bleiben
2. Stil: Episch, immersiv, wie ein Erzaehler in einem Hoerbuch
3. Sprache: Deutsch, gehoben aber verstaendlich
4. Laenge: Moderat erweitern, nicht zu lang (max. 2-3x Original)
5. Keine Anrede an den Spieler mit ""du"" - stattdessen ""Ihr"" oder passive Formulierungen
6. Platzhalter wie [NPC], [Zone] oder $n beibehalten

BEISPIEL:
Original: ""Toetet 8 Schweine und kehrt zurueck""
Optimiert: ""Begebt Euch zu den Feldern im Westen und bezwingt acht der wilden Schweine, die dort die Ernte bedrohen. Kehrt danach zurueck, um Eure wohlverdiente Belohnung zu erhalten.""

Antworte NUR mit dem optimierten Text, ohne Erklaerungen oder Kommentare.";

        /// <summary>
        /// Erstellt ein neues ManualTextGenerationWindow.
        /// </summary>
        /// <param name="quest">Quest deren Text optimiert werden soll</param>
        public ManualTextGenerationWindow(Quest quest)
        {
            InitializeComponent();

            _quest = quest ?? throw new ArgumentNullException(nameof(quest));
            _originalText = quest.AutoGeneratedTtsText;

            // Quest-Info anzeigen
            QuestInfoRun.Text = $"[{quest.QuestId}] {quest.Title} ({quest.Zone ?? "Unbekannt"})";

            // Prompt generieren
            PromptTextBox.Text = BuildFullPrompt();

            // TextChanged-Event fuer Zeichenzaehler
            ResponseTextBox.TextChanged += ResponseTextBox_TextChanged;
        }

        /// <summary>
        /// Baut den vollstaendigen Prompt fuer die KI.
        /// </summary>
        private string BuildFullPrompt()
        {
            var sb = new StringBuilder();

            // System-Prompt
            sb.AppendLine("=== SYSTEM-ANWEISUNG ===");
            sb.AppendLine(SystemPrompt);
            sb.AppendLine();

            // User-Prompt
            sb.AppendLine("=== QUEST ZUM OPTIMIEREN ===");
            sb.AppendLine();
            sb.AppendLine($"Quest-Titel: {_quest.Title}");
            sb.AppendLine($"Kontext: Zone: {_quest.Zone ?? "Unbekannt"}, Kategorie: {_quest.CategoryShortName}");
            sb.AppendLine();
            sb.AppendLine("Original-Text:");
            sb.AppendLine(_originalText);
            sb.AppendLine();
            sb.AppendLine("Bitte optimiere diesen Text fuer ein Hoerbuch:");

            return sb.ToString();
        }

        /// <summary>
        /// Handler fuer "KI-Prompt kopieren" Button.
        /// </summary>
        private void OnCopyPromptClick(object sender, RoutedEventArgs e)
        {
            try
            {
                Clipboard.SetText(PromptTextBox.Text);
                CopyStatusText.Text = "Kopiert!";

                // Nach 3 Sekunden wieder ausblenden
                var timer = new System.Windows.Threading.DispatcherTimer
                {
                    Interval = TimeSpan.FromSeconds(3)
                };
                timer.Tick += (s, args) =>
                {
                    CopyStatusText.Text = "";
                    timer.Stop();
                };
                timer.Start();
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Fehler beim Kopieren:\n{ex.Message}",
                    "Fehler",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// Handler fuer "Aus Zwischenablage einfuegen" Button.
        /// </summary>
        private void OnPasteResponseClick(object sender, RoutedEventArgs e)
        {
            try
            {
                if (Clipboard.ContainsText())
                {
                    ResponseTextBox.Text = Clipboard.GetText();
                }
                else
                {
                    MessageBox.Show(
                        "Die Zwischenablage enthaelt keinen Text.",
                        "Zwischenablage leer",
                        MessageBoxButton.OK, MessageBoxImage.Information);
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    $"Fehler beim Einfuegen:\n{ex.Message}",
                    "Fehler",
                    MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }

        /// <summary>
        /// Handler fuer TextChanged im Response-Textfeld.
        /// </summary>
        private void ResponseTextBox_TextChanged(object sender, System.Windows.Controls.TextChangedEventArgs e)
        {
            var text = ResponseTextBox.Text;
            var charCount = text?.Length ?? 0;

            CharCountText.Text = $"{charCount:N0} Zeichen";

            // Button aktivieren wenn Text vorhanden
            ApplyButton.IsEnabled = charCount > 10;

            // Vergleich anzeigen
            if (charCount > 10)
            {
                var originalLen = _originalText.Length;
                var diff = charCount - originalLen;
                var percent = originalLen > 0 ? (diff * 100.0 / originalLen) : 0;
                var sign = diff >= 0 ? "+" : "";
                ComparisonText.Text = $"Original: {originalLen:N0} Zeichen → Neu: {charCount:N0} Zeichen ({sign}{percent:F0}%)";
            }
            else
            {
                ComparisonText.Text = "";
            }
        }

        /// <summary>
        /// Handler fuer "KI-Text uebernehmen" Button.
        /// </summary>
        private void OnApplyClick(object sender, RoutedEventArgs e)
        {
            var responseText = ResponseTextBox.Text?.Trim();

            if (string.IsNullOrWhiteSpace(responseText))
            {
                MessageBox.Show(
                    "Bitte fuege zuerst den optimierten Text der KI ein.",
                    "Kein Text",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            // Minimal-Validierung: Text sollte nicht identisch sein
            if (responseText == _originalText)
            {
                var result = MessageBox.Show(
                    "Der eingegebene Text ist identisch mit dem Original.\n\n" +
                    "Trotzdem uebernehmen?",
                    "Text unveraendert",
                    MessageBoxButton.YesNo, MessageBoxImage.Question);

                if (result != MessageBoxResult.Yes) return;
            }

            EnhancedText = responseText;
            WasApplied = true;
            DialogResult = true;
            Close();
        }

        /// <summary>
        /// Handler fuer "Schliessen" Button.
        /// </summary>
        private void OnCloseClick(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
            Close();
        }
    }
}
